#pragma once

#define FPS 120
#define WINDOW_WIDTH 1200
#define WINDOW_HEIGHT 600

#define FONT_SIZE 32
#define PAST_COLOR WHITE
#define CURRENT_COLOR GRAY
#define FUTURE_COLOR LIGHTGRAY
#define MAX_LINE_SIZE 50
#define MAX_CHAR_MSG 300

#define MISTAKE_COLOR RED

#define BACKGROUD BLACK